### ISSUE TITLE
UserWarning because of empty Geometry column

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#105]
Our tests currently throw the following warning: 

> UserWarning: Geometry column does not contain geometry. warnings.warn("Geometry column does not contain geometry.")

I am not sure where exactly this originates but it is thrown for the following tests:

> tests/io/test_file.py::TestFile::test_triplegs_from_to_csv
> tests/io/test_file.py::TestFile::test_staypoints_from_to_csv
> tests/io/test_file.py::TestFile::test_locations_from_to_csv

**Comment by hong2223** [comment]
Nice! Already fixed this issue and will be integrated with the next pull request

**Comment by henrymartin1** [comment]
:D
