### ISSUE TITLE
Convention for format (and trackintel data types) in docstrings

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#117]
Hey, 
I was just writing docstrings and I noticed that many of things I write in docstrings are more or less random. 
Examples are:
- Datatypes:
   - Geopandas DataFrame / Geodataframe
   - trackintel staypoints / staypoints / staypoins in trackintel format / Geodataframe in trackintel staypoint format ...
   - Same for all other trackintel datatypes ;-)
- Format: I format docstrings in many different ways. Is there any convention?
    Example to describe a specific column name: 
     > - must have a column 'staypoint_id'
     > - must have a column staypoint_id
     > - must have a column `staypoint_id`
     > - etc.

I think we could add a section on docstrings in [contributing.md](https://github.com/mie-lab/trackintel/blob/master/CONTRIBUTING.md) where define some rules and maybe copy the most important parts from the official [numpy doc](https://numpydoc.readthedocs.io/en/latest/format.html)

**Comment by svenruf** [comment]
Yes definitely a agreement needed :) 
I think GeoDataFrame would be the correct spelling? I would not write GeoPandas each time, as we refer that trackintel is based on Pandas / GeoPandas in the readme.
For the trackintel "datatypes" maybe something like: 
- GeoDataFrame (as trackintel positionfixes)
- GeoDataFrame (validated as trackintel positionfixes)
- trackintel positionfixes (GeoDataFrame)

**Comment by henrymartin1** [comment]
We agreed on: 
- Geopandas: GeoDataFrame
- Trackintel datatypes: 
   - GeoDataFrame (as trackintel positionfixes)
   - GeoDataFrame (as trackintel staypoints)
   - ...

This should be added to contributing.md

**Comment by henrymartin1** [comment]
We agreed on: 
- the `examples` section is mandatory in new docstrings
