### ISSUE TITLE
Ensure generated id starts from 0

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#119]
`Agg_level='user'` option in `generate_locations` function generates `id` starting from 1, which is not consistent with `Agg_level='dataset'`. Need to have ids starting from 0.
Tests for this issue are also needed.

**Comment by henrymartin1** [comment]
Wasn't this solved by the last pull request? #120

**Comment by hong2223** [comment]
Tests for id generation for all functions are still missing
