### ISSUE TITLE
Inconsistent naming for io functions

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#129]
At the moment we have:
- `read_positionfixes_csv`
- `read_positionfixes_postgis`
- `positionfixes_from_gpd`
So I would propose that we rename `positionfixes_from_gpd` to `read_positionfixes_gpd`

**Comment by svenruf** [comment]
I originally named it like this, but in a meeting the argument (don't remember from who) was that it isn't actually a reading function, as it does only import/rename the GeoDataFrame. So I changed the name 😄

**Comment by henrymartin1** [comment]
I think i can remember this 😬. I just tried using it and found it weird that it is named differently...

**Comment by henrymartin1** [comment]
We agreed on double checking if pandas makes a distinction between reading and loading if it is not external. If there is no distinction, then we can rename the function in `read_positionfixes_gpd`
