### ISSUE TITLE
generate_staypoints produce stps with duration smaller than time_threshold

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#132]
Some of the `stps` generated by the function have very short durations (even 0). The problem is in file `trackintel\trackintel\preprocessing\positionfixes.py`

I am not very sure the cause, but it seems `delta_t` and the `if` statement in Line 308 is correct, but in Line 319 `staypoint['finished_at'] = pfs[j - 1]['tracked_at']` the `j-1` is different than `j` used elsewhere.

**Comment by henrymartin1** [comment]
Strange indeed. I can have a look but is it possible for you to provide sample data for this?

**Comment by hong2223** [comment]
> Strange indeed. I can have a look but is it possible for you to provide sample data for this?

you could run 
`pfs = ti.io.dataset_reader.read_geolife(os.path.join('tests', 'data', 'geolife_long'))`
`pfs, stps = pfs.as_positionfixes.generate_staypoints(method='sliding', dist_threshold=25, time_threshold=5 * 60)`
and check the `stps`
