### ISSUE TITLE
add a test that runs all examples

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#139]
I think it would be a good idea to test if the examples are still working after we committed changes. An Idea to do this would be to have a test that simply runs all examples. Without that it will be hard to keep the examples up-to-date and running.

**Comment by svenruf** [comment]
#185 will only add a test for the tutorial. 
I thought about completing the test file that runs now the tutorial with tests that run the (other) examples. Do you think you will keep these examples? Then i'm going to add these.

**Comment by hong2223** [comment]
Sure, that would be a great addition!
From what I can see, we only have `examples\preprocess_trajectories.py` in the example folder that can be tested. The other files are related to postGIS and need to wait for #168. Is that correct?

**Comment by svenruf** [comment]
Yes, seems to me that this is the case. I added a test file and class for eventual future examples and included a test for preprocess_trajectories.py
