### ISSUE TITLE
Code style using black

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#144]
We could consider using [black](https://github.com/psf/black) as our code formatter. 
They provide [GitHub Actions](https://github.com/psf/black/blob/master/README.md#github-actions) for formatting the pull requests.
We can then also add their [badge](https://img.shields.io/badge/code%20style-black-000000.svg)

**Comment by henrymartin1** [comment]
Yes! I am strongly in favor. We just have to make sure that we have a single pull request that changes the codestyle in all files and does nothing else. 
We also have to make sure that we have the same configuration for black. I would be OK with the default even if this means to switch to a line length of 79 characters.
