### ISSUE TITLE
Plotting of locations/staypoints as circles.

### ISSUE THREAD

**Issue by bifbof** [mie-lab/trackintel#169]
In PR #135 we saw that our staypoints are plotted as ellipses rather than circles.
For a better understanding (circle = same distance) we should change that.
We think that the problem lies in the unequal aspect ratio of the plot.
To fix that we should change how the `regular_figure()` function works and either hard code the same aspect ratio for the **axis** (not figure) or add an additional keyword `aspect="equal"`.

Reference:
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_aspect.html

**Comment by hong2223** [comment]
Thanks for the proposed fix. Both are fine. 
For now, I am in favor of hardcoding the same aspect ratio; I cannot imagine why the user would like to have an ellipse.
