### ISSUE TITLE
Description of data model missing

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#19]
We should have a page about our data model in the documentation. I think at the moment the data model is only defined in the sql folder...

**Comment by henrymartin1** [comment]
Things that should be updated in the data model:
- Geometry column can have an arbitrary name
- Timestamp formats should be defined

**Comment by dominikbucher** [comment]
There are the following two pages:

https://trackintel.readthedocs.io/en/latest/modules/model.html
https://trackintel.readthedocs.io/en/latest/content/data_model_sql.html

I like having the SQL model as ground truth as it's very formal and doesn't leave (much) room for ambiguity. But the first of the two pages should be updated and expanded, so we can explain the model in more detail and more informally.

**Comment by henrymartin1** [comment]
I agree that there are advantages for having the SQL documentation but it will be extra effort to keep everything in sync
