### ISSUE TITLE
ENH: Speed calculation for triplegs/positionfixes

### ISSUE THREAD

**Issue by svenruf** [mie-lab/trackintel#191]
during my internship I once used movingpandas to calculate speeds per positionfix and mean speeds for triplegs (for delay classification of measurement on a bus).

In the last meeting we agreed that this could also be useful in the future for trackintel 2.0

at the moment the transport mode prediction does a mean speed calculation for quick classification of transport modes

**Comment by abcnishant007** [comment]
@hong2223  Following up on the discussion today. 
A nice explanation of the differences between `space_mean` and `time_mean` speed can be found on page 1 of [this](https://nptel.ac.in/content/storage2/courses/105101087/downloads/Lec-31.pdf) document. 
Please let me know if you want to discuss further.
