### ISSUE TITLE
BUG: generate_staypoints and generate_trips

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#203]
if the input pfs already has a column `staypoint_id`, the following error will occur on Line 144

`ValueError: columns overlap but no suffix specified: Index(['staypoint_id'], dtype='object')`

**Comment by hong2223** [comment]
a similar error is observed in generate_trips on line 137:

`ValueError: columns overlap but no suffix specified: Index(['trip_id'], dtype='object')`

**Comment by abcnishant007** [comment]
@hong2223 **generate_trips** does not seem to have this problem, I think you had renamed it based on our guess yesterday.
Later I checked but did not find the problem, please feel free to verify from your end.

**Comment by hong2223** [comment]
> a similar error is observed in generate_trips on line 137:
> 
> `ValueError: columns overlap but no suffix specified: Index(['trip_id'], dtype='object')`

I still observe this error in `generate_trips` on line 137 when calling the function twice, e.g.,: 
`stps, tpls, trips = ti.preprocessing.triplegs.generate_trips(stps, tpls, gap_threshold=15)`
`stps, tpls, trips = ti.preprocessing.triplegs.generate_trips(stps, tpls, gap_threshold=15)`

the second line will fail because there is already a `trip_id` column assigned for `tpls`
