### ISSUE TITLE
Add documentation to accessor methods.

### ISSUE THREAD

**Issue by bifbof** [mie-lab/trackintel#209]
The accessor functions with the pattern `as_triplegs.xyz` do not have a complete documentation, but rather refer to the wrapped functions in a different modules. This is inconvenient for working in an editor, as one cannot look up the functionality of the various parameters in the docstring. Instead one has to look up the referenced docstring seperatly.

Two ways to change that would be:
1. Just copy the docstring over at every change. 
2. Use a decorator to copy the docstring directly.

The first way is rather error-prone as one has to remember to change both docstrings at any change. Here it would be good to write a test that checks the equality of the `__doc__` attribute of the functions. The second way can be unclear in the documentation as it replaces silently the existing docstring. Also other problem arises in terms of circular imports etc. .

**Comment by henrymartin1** [comment]
Here is an additional point from #228 (point 8) that should be solved in this issue: 

>I think that using preprocessing methods via the accessors is somehow poorly documented. If using the accessors is the standard way it might be useful to mention them in the docstring of the method so that users will know that they can use a specific method via the accessor. It is sometimes not clear to me (as a maintainer^^) which methods are available via the accessor. Having the accessor written out in the doc string would also help because I could then simply copy the code from the documentation.

**Comment by henrymartin1** [comment]
Would using @wraps solve this issue?
