### ISSUE TITLE
Fix official abbrevations for trackintel datatypes

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#214]
In the code we are often using abbrevations to name variables we had this [discussion a while ago in a pull request](https://github.com/mie-lab/trackintel/pull/155#discussion_r594355723) but we never resolved it.

I think at the moment we commonly use: 
- triplegs: tpls
- positionfixes: pfs
- staypoints: spts vs stps

It would be nice to agree on a set of abbrevations and write it into CONTRIBUTING.md.

Personally I am in favor of spts as it reminds me of points which is often shortend as **pts**.
I don't really like tpls because to me it seems as if we would just pick random letters from the word *triplegs* but I can live with it as it seems quite consitent in the framework.

**Comment by hong2223** [comment]
we agree on **staypoints: sp**
