### ISSUE TITLE
Enable trackintel datatype asserts via accessor

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#215]
We often use the accessor in an assert statement 
e.g., 
```Python
assert spts.as_staypoints
```
However, I think at the moment this is not really correct. I think the input to an ```assert``` should be boolean and either be True or False. The accessors call the ```__init__``` method (e.g., [for staypoints](https://github.com/mie-lab/trackintel/blob/master/trackintel/model/staypoints.py#L39)) which calls ```self._validate()```. At the moment our ```_validate``` method does not return True or False, it simply fails internally (which kind of works in the end).
In general I don't think that this is a super serious problem but the following would not give the expected results:
```Python
assert spts.as_staypoints, "This assert failed, therefore I show my custom assert message"
```
In that case the custom assert message would not be shown as an internal assertion error is raised instead. 

To fix it, we could either stop writing 
```Python
assert spts.as_staypoints
```
but instead write
```Python
spts.as_staypoints
```
which would lead the same results but is less readable. Or we would add a wrapper function that returns a boolean. 
E.g.

```Python
assert spts.as_staypoints.is_valid
```` 

I think a great advantage of the first option is that it explains the user why the assert fails (as we have very descriptive internal assert messages)

**Comment by hong2223** [comment]
We agreed to change the assert statement
```Python
assert spts.as_staypoints
```
into 
```Python
spts.as_staypoints
```
(delete `assert`) and add a comment saying this line is validating the dataframe.

This change affects all read functions from `file.py`, `from_geopandas.py` and `postgis.py`
