### ISSUE TITLE
Some minor points I noticed while using trackintel

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#228]
1. In the `read_geolife` doc it says that returning labels is optional while it always returns labels. [link](https://trackintel.readthedocs.io/en/latest/modules/io.html#trackintel.io.dataset_reader.read_geolife)
2. The printing of progress in the geolife dataset reader should be optional
3. It would be great if `geolife_add_modes_to_triplegs` would have an example available
4. I think the explanation of `gap_threshold ` in `generate_staypoints` is not very clear. We should add a section under notes that briefly explains that positionfixes with a time distance that is greater than `gap_threshold` are excluded from a staypoint.
5. I think the default value of `gap_threshold ` in `generate_staypoints` should be something useful (e.g., 15 minutes as suggested in the notes) or nan/None/Null/inf/False to make clear that it is not used by default.
6. I think the documentation style of writing dark blue on light blue for the function definition has very bad contrast e.g., [here](https://trackintel.readthedocs.io/en/latest/modules/preprocessing.html#trackintel.preprocessing.positionfixes.generate_triplegs)
7. The clarification `if ‘distance_metric’ is ‘haversine’ or ‘euclidean’, the unit is in meters.` (from `generate_locations`) should be copied to `generate_staypoints`.
8. I think that using preprocessing methods via the accessors is somehow poorly documented. If using the accessors is the standard way it might be useful to mention them in the docstring of the method so that users will know that they can use a specific method via the accessor. It is sometimes not clear to me (as a maintainer^^) which methods are available via the accessor. Having the accessor written out in the doc string would also help because I could then simply copy the code from the documentation.
9. I think the default value of 5 minutes as a time threshold for [create_activity_flag](https://trackintel.readthedocs.io/en/latest/modules/analysis.html#trackintel.analysis.label.create_activity_flag) should be increase to 15
10. The example in [trip generation](https://trackintel.readthedocs.io/en/latest/modules/preprocessing.html#trackintel.preprocessing.triplegs.generate_trips) should show the usage of the accessor
11. The documentation of the [geolife dataset reader](https://trackintel.readthedocs.io/en/latest/modules/io.html#trackintel.io.dataset_reader.read_geolife) should mention that we support reading of mode labels.
12. I think the category `Label` in the [documentation ](https://trackintel.readthedocs.io/en/latest/modules/analysis.html#label) should rather be called `Labeling`.
13. `geolife_add_modes_to_triplegs` is not in documentation ❗ 
14. The example in [generate_trips](https://trackintel.readthedocs.io/en/latest/modules/preprocessing.html#trackintel.preprocessing.triplegs.generate_trips) should show the full path of the `generate_trips` function. E.g., `trackintel.preprocessing.triplegs.generate_trips`
15. `generate_trips` is shown under preprocessing/triplegs but it is not available via a tripleg accessor. Maybe it should be moved to analysis?

**Comment by hong2223** [comment]
1. My understanding is the labels are optional for the geolife reading. But the doc definitely needs to clarify. Do we want the read_geolife function to always return labels? we can also add a flag to control the return.
2. :heavy_check_mark:
3. :heavy_check_mark:. And also, I could not find this function in the doc, I think we need to add it somewhere. (same as 13)
4. :heavy_check_mark:. I have not extensively tested the behaviour of setting `gap_threshold` to a small value (by default it is not used). Need to be done.
5. :heavy_check_mark:
6. :heavy_check_mark:
7. :heavy_check_mark:
8. :heavy_check_mark:
9. :heavy_check_mark:
10. :heavy_check_mark:
11. :heavy_check_mark:
12. :heavy_check_mark:. That also means we need to change the file name.
13. :heavy_check_mark:
14. :heavy_check_mark:
15. I would try to keep it in preprocessing, as it is still the process of climbing up the hierarchy. We could add it in the accessor

**Comment by henrymartin1** [comment]
I just created pull request #234 that address the majority of these issues. Below I propose what to do with the others.

1. ~In the `read_geolife` doc it says that returning labels is optional while it always returns labels. [link] (https://trackintel.readthedocs.io/en/latest/modules/io.html#trackintel.io.dataset_reader.read_geolife)~
➡️  `read_geolife` now returns labels by default because it is only parsing files and does not cost much performance to read them.
2. ~The printing of progress in the geolife dataset reader should be optional~
3. ~It would be great if `geolife_add_modes_to_triplegs` would have an example available~
4. I think the explanation of `gap_threshold ` in `generate_staypoints` is not very clear. We should add a section under notes that briefly explains that positionfixes with a time distance that is greater than `gap_threshold` are excluded from a staypoint.
5. I think the default value of `gap_threshold ` in `generate_staypoints` should be something useful (e.g., 15 minutes as suggested in the notes) or nan/None/Null/inf/False to make clear that it is not used by default.
6. I think the documentation style of writing dark blue on light blue for the function definition has very bad contrast e.g., [here](https://trackintel.readthedocs.io/en/latest/modules/preprocessing.html#trackintel.preprocessing.positionfixes.generate_triplegs)
7. ~The clarification `if ‘distance_metric’ is ‘haversine’ or ‘euclidean’, the unit is in meters.` (from `generate_locations`) should be copied to `generate_staypoints`.~
8. I think that using preprocessing methods via the accessors is somehow poorly documented. If using the accessors is the standard way it might be useful to mention them in the docstring of the method so that users will know that they can use a specific method via the accessor. It is sometimes not clear to me (as a maintainer^^) which methods are available via the accessor. Having the accessor written out in the doc string would also help because I could then simply copy the code from the documentation.
9. ~I think the default value of 5 minutes as a time threshold for [create_activity_flag](https://trackintel.readthedocs.io/en/latest/modules/analysis.html#trackintel.analysis.label.create_activity_flag) should be increase to 15~
10. ~The example in [trip generation](https://trackintel.readthedocs.io/en/latest/modules/preprocessing.html#trackintel.preprocessing.triplegs.generate_trips) should show the usage of the accessor~
11. ~The documentation of the [geolife dataset reader](https://trackintel.readthedocs.io/en/latest/modules/io.html#trackintel.io.dataset_reader.read_geolife) should mention that we support reading of mode labels.~
12. I think the category `Label` in the [documentation ](https://trackintel.readthedocs.io/en/latest/modules/analysis.html#label) should rather be called `Labeling`.
13. ~`geolife_add_modes_to_triplegs` is not in documentation~
14. ~The example in [generate_trips](https://trackintel.readthedocs.io/en/latest/modules/preprocessing.html#trackintel.preprocessing.triplegs.generate_trips) should show the full path of the `generate_trips` function. E.g., `trackintel.preprocessing.triplegs.generate_trips`~ (fixed in a prior commit)
15. ~`generate_trips` is shown under preprocessing/triplegs but it is not available via a tripleg accessor. Maybe it should be moved to analysis?~

Here are my propositions for the other issues: 
- move 4+5 in an extra issue that is related to the `generate_location` function
- add 6 to #226 
- add 8 to #209 
- create extra issue for 12

**Comment by abcnishant007** [comment]
@henrymartin1 added 6 to #226 and assigned to myself

**Comment by henrymartin1** [comment]
I added 8 to #209
