### ISSUE TITLE
functions from location_identification.py are not discoverable

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#241]
```
>>> trackintel.analysis.location_identification
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'trackintel.analysis' has no attribute 'location_identification'
```

```
>>> import trackintel
>>> dir(trackintel.analysis)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'calculate_haversine_length', 'calculate_modal_split', 'check_gdf_crs', 'create_activity_flag', 'datetime', 'label', 'modal_split', 'np', 'pd', 'predict_transport_mode', 'temporal_tracking_quality', 'tracking_quality']
```
not how `dir(trackintel.analysis)` shows `modal_split`, `label` and the function from `tracking_quality`

I guess it is because it is not in the `__init__.py `

**Comment by bifbof** [comment]
I'll saw that one as well. :) It will be fixed in the OSNA-PR.

**Comment by henrymartin1** [comment]
Nice, then I'll assign the issue to you

**Comment by hong2223** [comment]
Maybe related: When generating our documentation:

> AttributeError: module 'trackintel.analysis.location_identification' has no attribute 'freq_recipe'

**Comment by henrymartin1** [comment]
I think I saw @abcnishant007 fixing this in #237 [here](https://github.com/mie-lab/trackintel/pull/237/files#diff-633d6d98079847548ce459a7ca0e344ccc4383217e9782e5a617636486562d36R31)

**Comment by hong2223** [comment]
> > Maybe related: When generating our documentation:
> > > AttributeError: module 'trackintel.analysis.location_identification' has no attribute 'freq_recipe'
> 
> I think I saw @abcnishant007 fixing this in #237 [here](https://github.com/mie-lab/trackintel/pull/237/files#diff-633d6d98079847548ce459a7ca0e344ccc4383217e9782e5a617636486562d36R31)

The error still occurs after changing the function name. I think we need to import 'freq_method' in the `trackintel\analysis\__init__.py` file for the doc to recognize. Maybe you can also add this import? @bifbof

**Comment by hong2223** [comment]
This shall now be solved by **ENH: Fix init.py and label module** #252
