### ISSUE TITLE
all write_*_postgis function do not use the schema

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#243]
E.g. [here](https://github.com/mie-lab/trackintel/blob/master/trackintel/io/postgis.py#L147)

In general I think that these wrapper functions should allow setting all variables from geopandas' [to_postgis](https://geopandas.org/docs/reference/api/geopandas.GeoDataFrame.to_postgis.html#geopandas.GeoDataFrame.to_postgis) function.

**Comment by bifbof** [comment]
In PR #264 I added the schema argument to each `to_postgis` function. 
Should we add the others in that PR as well? 
The missing arguments (index and dtype) except index_label are used anyway, we may need to make our reading_*_postgis functions more flexible to accommodate this change.
