### ISSUE TITLE
trackintel-postgis connector fails when using mixed timezones

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#249]
reading staypoints from a postgis database with timestamps with mixed timezones results in the following error when using `assert spts.as_staypoints`: 
```
  File "C:\Users\henry\.conda\envs\graph_rep\lib\site-packages\trackintel\model\staypoints.py", line 60, in _validate
    assert pd.api.types.is_datetime64tz_dtype(
AssertionError: dtype of started_at is object but has to be tz aware datetime64
```
This seems to be a pandas-posgresql problem where we can not do much about it but we can solve the problem by transforming data to UTC after reading it from the database.
```python
for col in ['started_at', 'finished_at']:
     spts[col] = pd.to_datetime(spts[col], utc=True)
```
I have ran some quick tests and what it does is that transforms the timezone to UTC without losing the time information (e.g., 13:33+02 -->11:33+00) however I am not sure what happens if no tz is provided

**Comment by bifbof** [comment]
So I tried to replicate this problem but it seems that postgresql does not save any time zone information everything is in UTC or to quote the [postgres documentation](www.postgresql.org/docs/9.1/datatype-datetime.html).

> When a timestamp with time zone value is output, it is always converted from UTC to the current timezone zone, and displayed as local time in that zone. To see the time in another time zone, either change timezone or use the AT TIME ZONE construct (see Section 9.9.3).

The `timestamp with time zone` is only there for parsing the input right.
I reproduced that issue also in code with the same result.

```python
import psycopg2
import trackintel as ti
import geopandas as gpd
import os

con = psycopg2.connect(conn_string)
cur = con.cursor()

sql = """
CREATE TABLE positionfixes (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    tracked_at timestamp with time zone NOT NULL,
    geom geometry(Point, 4326),
    CONSTRAINT positionfixes_pkey PRIMARY KEY (id)
);
"""
cur.execute(sql)
con.commit()

sql = """
INSERT INTO positionfixes VALUES
(0, 0, timezone('-5', '2021-08-01 16:00:00'), ST_GeomFromText('POINT(-71.064544 42.28787)')),
(1, 0, timezone('+8', '2021-08-01 15:00:00'), ST_GeomFromText('POINT(103.773681 1.30409)')),
(2, 0, timezone('+1', '2021-08-01 14:00:00'), ST_GeomFromText('POINT(8.506545 47.40876)'));
"""
cur.execute(sql)
con.commit()

pfs = ti.io.read_positionfixes_postgis("SELECT * FROM positionfixes_test", conn_string, "geom")
print(pfs)
con.close()
```

And in the pfs and while looking at it through PgAdmin I see only the local timezone information attached to it.

**Comment by henrymartin1** [comment]
Hm... I encountered the same problem again... very annoying. I had a look at your script (thanks a lot for that!) and what happens in the database and a lot of weirdness is going on. I always makes me sad when I think about how much energy is spend world wide on timezone errors...
So it seems that everything gets transformed into the same timezone in postgresql, which is great. Except if you change from summer time to winter time 🎉 Then you get two different timezones and the problem starts. I have altered your script to reproduce the error:
```sql
import psycopg2
import trackintel as ti
import geopandas as gpd
import os
from sqlalchemy import create_engine
from db_login import DSN

conn_string = "postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_database}".format(**DSN)

con = psycopg2.connect(conn_string)
cur = con.cursor()

sql = """DROP TABLE IF EXISTS henry_dev.bug249"""
cur.execute(sql)
con.commit()

sql = """
CREATE TABLE henry_dev.bug249 (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    tracked_at timestamp with time zone NOT NULL,
    geom geometry(Point, 4326),
    CONSTRAINT positionfixes_pkey PRIMARY KEY (id)
);
"""
cur.execute(sql)
con.commit()

sql = """
INSERT INTO henry_dev.bug249 VALUES
(0, 0, timezone('-5', '2021-08-01 16:00:00'), ST_SetSRID(ST_GeomFromText('POINT(-71.064544 42.28787)'), 4326)),
(1, 0, timezone('+8', '2021-08-01 15:00:00'), ST_SetSRID(ST_GeomFromText('POINT(103.773681 1.30409)'), 4326)),
(2, 0, timezone('+1', '2021-02-01 14:00:00'), ST_SetSRID(ST_GeomFromText('POINT(8.506545 47.40876)'), 4326));
"""
cur.execute(sql)
con.commit()

pfs = ti.io.read_positionfixes_postgis("SELECT * FROM henry_dev.bug249", conn_string, "geom")
print(pfs)
con.close()
```

(I change the table name...)

I could fix the problem by including
```python
    if tz_cols is not None:
        for col in tz_cols:
            if not pd.api.types.is_datetime64tz_dtype(gdf[col]):
                try:
                    gdf[col] = _localize_timestamp(dt_series=gdf[col], pytz_tzinfo=tz, col_name=col)
                except ValueError:
                    gdf[col] = pd.to_datetime(gdf[col], utc=True)
```
in `from geopandas`

**Comment by bifbof** [comment]
Oh man... Great catch tho, I never would have thought of that.
At least we know that we can transform it savely to UTC as it was saved that way.
PR will follow soon. :)
