### ISSUE TITLE
ValueError when generating trip legs for full Geolife dataset

### ISSUE THREAD

**Issue by NinaWie** [mie-lab/trackintel#266]
When I try to generate triplets for the full Geolife dataset, (`pfs_full.as_positionfixes.generate_triplegs`) I get the following error:
`ValueError: LineStrings must have at least 2 coordinate tuples`

The error occurs [here](https://github.com/mie-lab/trackintel/blob/2108bbb8545365b5e89dc53cf25694af2a9dede6/trackintel/preprocessing/positionfixes.py#L363) in the following line: 
`tpls["geom"] = tpls["geom"].apply(LineString)`

However, in Line 339 [here](https://github.com/mie-lab/trackintel/blob/2108bbb8545365b5e89dc53cf25694af2a9dede6/trackintel/preprocessing/positionfixes.py#L339) it should be ensured that each line string has at least two points, so it must be some special case in the dataset.

To reproduce on smaller dataset: It happens for example also if only generating triplegs for user 10.

**Comment by henrymartin1** [comment]
Thanks for the report and for looking into the origin. Can you check if this was solved by #238 ? 
#238 is already available in the newest version (1.1.1) on pip.

**Comment by NinaWie** [comment]
Yes, issues seem solved :) Will close this issue then
