### ISSUE TITLE
trackintel generate functions are not allowed to return empty dataframes

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#267]
At the moment it is not possible to call our generate functions when the result would be empty. 
I think it is an OK use-case that you try to generate a trackintel object (e.g., by using generate_triplegs) without knowing if there are valid triplegs in the set of positionfixes. 

The reason for this behavior is that we usually call the accessor for validation within the generator function e.g. `assert tpls.as_triplegs` and the accessor asserts that the dataframe is not empty. E.g., `assert obj.shape[0] > 0, "Geodataframe is empty with shape: {}".format(obj.shape)`

Possible ways to fix this would be to not call the accessor for validation in the generator functions (maybe replace it with a validation function?) or change the validation in the accessor.

Here is a code example: 

```python
import pandas as pd
import geopandas as gpd
import trackintel as ti
from shapely.geometry import Point

p1 = Point(8.5067847, 47.4)
p2 = Point(8.5067847, 47.5)
p3 = Point(8.5067847, 47.6)

t1 = pd.Timestamp("1971-01-01 00:00:00", tz="utc")
t2 = pd.Timestamp("1971-01-02 01:01:00", tz="utc")
t3 = pd.Timestamp("1971-01-02 01:02:00", tz="utc")
t4 = pd.Timestamp("1971-01-01 03:00:00", tz="utc")

list_dict = [
    {"user_id": 0, "tracked_at": t1, "geometry": p1, "staypoint_id": 0},
    {"user_id": 0, "tracked_at": t2, "geometry": p2, "staypoint_id": pd.NA},
    {"user_id": 1, "tracked_at": t3, "geometry": p2, "staypoint_id": pd.NA},
    {"user_id": 1, "tracked_at": t4, "geometry": p3, "staypoint_id": 1}
]
pfs = gpd.GeoDataFrame(data=list_dict, geometry="geometry", crs="EPSG:4326")
pfs.index.name = "id"
assert pfs.as_positionfixes

pfs, tpls = pfs.as_positionfixes.generate_triplegs()


```

**Comment by hong2223** [comment]
We agreed to add an if statement to bypass the assert if the generated df is empty
