### ISSUE TITLE
Remote Repository using VScode

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#269]
VScode recently introduced a new feature [Remote Repositories](https://code.visualstudio.com/blogs/2021/06/10/remote-repositories) which enables accessing repo remotely without cloning it on the local machine. They introduced a new badge (check the first badge here https://github.com/microsoft/vscode) that will trigger this functionality just at the front page.

I think this is a nice function to integrate and help outside users familiarize trackintel.

**Comment by henrymartin1** [comment]
I was in as soon as I read "new badge" ;-)
So its like a binder that you run locally?

**Comment by hong2223** [comment]
Yes! Clicking the badge would directly open trackintel in your local vscode, without fetch/download/set up a local folder to store the repo. 

I was testing the functionality, but accidentally "commit" my changes (= =!), now you can try this now on our main page...

Was not my intention to include that without a pull request, we could delete this if it is not useful.

**Comment by hong2223** [comment]
I am checking the manual for the [Remote Repositories](https://code.visualstudio.com/blogs/2021/06/10/remote-repositories). 

> When you commit changes, they'll automatically show up on GitHub – you don't need to push your changes or publish any new branches you create.

For us (developers with writing rights), the best is we use the remote functionality on our forked repo so that we do not accidentally commit changes directly to the main branch.

For users and visitors, the advantage is that they can view trackintel code in just two clicks (and without clone), potentially easier for them to contribute.

**Comment by henrymartin1** [comment]
The badge looks nice, I can not really test it because I am not using vscode. I think it is OK to have such small changes without pull request... 

I agree what you said about not using it with write access ;-)
