### ISSUE TITLE
Tripleg extraction is vulnerable to gaps in tracking data

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#27]
At the moment, the triplegs are defined as all trackpoints between two staypoints. While this is often correct, we should make sure, that gaps in the tracking data are dealt with. Otherwise, this could lead to triplegs that span over multiple days. Here is an example: 
![grafik](https://user-images.githubusercontent.com/31069329/95238990-9ce6d200-080a-11eb-9e21-10f288000f48.png)

![grafik](https://user-images.githubusercontent.com/31069329/95238926-82acf400-080a-11eb-8774-74a06b290789.png)

Here is code to reproduce the results (to look at it in QGIS)
```python
pfs = read_geolife(os.path.join('examples', 'example_geolife', 'rawdata_geolife'))
spts = pfs.as_positionfixes.extract_staypoints(method='sliding', dist_threshold=25, time_threshold=5 * 60)
tpls = pfs.as_positionfixes.extract_triplegs(spts)
pfs.to_file("posfix.geojson", driver='GeoJSON')
spts.to_file("stp.geojson", driver='GeoJSON')
tpls.to_file("triplegs.geojson", driver='GeoJSON') ```

**Comment by svenruf** [comment]
@henrymartin1 should it be possible to pass a threshold or do we define a fixed value for the max gap allowed?

**Comment by henrymartin1** [comment]
I think it would be better to pass a threshold. Anybody has an idea for a default threshold value? Whats the typical duration for long tunnels in Switzerland? :D

**Comment by svenruf** [comment]
Ok, then I will implement this. I think with 20 min the long tunnels are covered (gotthard base tunnel 17 min, gotthard street tunnel 13min).

**Comment by svenruf** [comment]
I just saw that for the trips, the gap_threshold default is 15min... I think we can talk about this, the default value is also easy to change after the implementation :)

**Comment by henrymartin1** [comment]
We agreed on reformulating the trip generation code in a simpler way.
