### ISSUE TITLE
Write locations with extent to postgis throws error

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#285]
Hi, 
I have tried to write locations with extent to a postgis database but I received an error. Here is an example that is very similar to the existing test:

```python
from shapely.geometry import Point, Polygon
import geopandas as gpd
from sqlalchemy import create_engine
import trackintel as ti
from db_login import DSN  # database login information
import numpy as np

engine = create_engine(
    "postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_database}".format(
        **DSN
    )
)

p1 = Point(8.5067847, 47.4)
p2 = Point(8.5067847, 47.5)
p3 = Point(8.5067847, 47.6)

list_dict = [
    {"user_id": 0, "center": p1},
    {"user_id": 0, "center": p2},
    {"user_id": 1, "center": p3},
]
locs = gpd.GeoDataFrame(data=list_dict, geometry="center", crs="EPSG:4326")
locs.index.name = "id"

coords = [[8.45, 47.6], [8.45, 47.4], [8.55, 47.4], [8.55, 47.6], [8.45, 47.6]]
extent = Polygon(coords)
locs["extent"] = extent  # broadcasting
locs["extent"] = gpd.GeoSeries(locs["extent"])  # dtype

locs.as_locations.to_postgis(name='locations', con=engine, schema="yumuv_graph_rep", if_exists='replace')
```
This throws the following error: 

```
psycopg2.errors.InvalidParameterValue: Geometry SRID (0) does not match column SRID (4326)
CONTEXT:  COPY locations, line 1, column extent: "POLYGON ((8.449999999999999 47.6, 8.449999999999999 47.4, 8.550000000000001 47.4, 8.550000000000001 ..."
```

I am honestly not really sure why as it is very similar to the existing test for locations. I could solve this by replacing [line 238](https://github.com/mie-lab/trackintel/blob/master/trackintel/io/postgis.py#L238)
`locations["extent"] = locations["extent"].apply(lambda x: WKTElement(x.wkt, srid=srid))` with the following:
`locations = gpd.GeoDataFrame(_convert_to_ewkb(locations, 'extent', srid), geometry='center', crs=srid)`

`_convert_to_ewkb` is a function from geopandas and can be imported `from geopandas.io.sql import _convert_to_ewkb`. This function is used in Geopandas to prepare the main geometry [link](https://github.com/geopandas/geopandas/blob/master/geopandas/io/sql.py#L402)

**Comment by bifbof** [comment]
Hmm I'm not sure what is causing, can't reproduce the error either :/ My ideas would be:
Either the WKTElement is not taken over correctly from postgis. That wouldn't really make sense since it's built for that support. Or postgis enters an unknown srid (0) somewhere that conflicts with the gdf srid (4326), and maybe something is hardcoded in the wkb solves that.

**Comment by henrymartin1** [comment]
yes, strange indeed... Maybe it could be an issue with the postgresql/postgis version of the database?

**Comment by henrymartin1** [comment]
I got this error with the following versions: 
- PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
- PostGIS 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
- Geopandas '0.8.1'

Our Ci actually installs postgis (without explicitly installing postgresql!) using conda (see [here](https://github.com/mie-lab/trackintel/runs/3182244481?check_suite_focus=true#step:6:22)). It probably always takes the most recent versions in our case it is postgis 3.1.3 and [postgresql 13.3](https://github.com/mie-lab/trackintel/runs/3182244481?check_suite_focus=true#step:6:22). I am suprised that I had so little idea of what is actually going on there :D
I think extending our pipeline to cover multiple versions of postgis would be an overkill ;-) 

I think it is a good idea to change it so that it uses `_convert_to_ewkb` from geopandas as long as it keeps working on the most recent version. What do you think?

**Comment by bifbof** [comment]
For me it works fine with:

- PostgreSQL 12.2, compiled by Visual C++ build 1914, 64-bit
- POSTGIS="3.1.1 3.1.1" [EXTENSION] PGSQL="120" GEOS="3.9.1-CAPI-1.14.1" PROJ="7.1.1" LIBXML="2.9.9" LIBJSON="0.12" LIBPROTOBUF="1.2.1" WAGYU="0.5.0 (Internal)"
- Geopandas '0.9.0'

I don't like changing something that I understand. ^^ But as it is just another way to do it, I'm okay with it.
