### ISSUE TITLE
rename optional columns "origin_activity" for trips

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#286]
Staypoints have the optional column: `purpose` [doc](https://trackintel.readthedocs.io/en/latest/modules/model.html#staypointsaccessor)
Trips have the optional columns: `origin_activity` and `destination_activity` [doc](https://trackintel.readthedocs.io/en/latest/modules/model.html#staypointsaccessor)
Proposition: Rename the optional columns for trips to: `origin_purpose` and `destination_purpose`
An alternative would be to rename the staypoint column to `activity_label` (this would be a bit more work)

**Comment by hong2223** [comment]
Related to this:

In the readme.md datamodel section we wrote `activities`, but `activities` is not part of our datamodel. Since the concept of activity is important in the theoretical movement datamodel, we decided to keep the description of activity, but wrote it as a subpoint of staypoints
