### ISSUE TITLE
Typo in warning in generate_trip

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#293]
It says spts instead of tpls [here](https://github.com/mie-lab/trackintel/blob/33d6205475ad8c4a859a9a5883241fe1098997b2/trackintel/preprocessing/triplegs.py#L118)

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by henrymartin1** [comment]
Hey @RhnSharma thank for your interest in trackintel and your motivation to contribute to the framework! Your contribution is very welcome!
Unfortunatly I have double checked the issue and I made a mistake by opening it. The warning is actually correct. Sorry for the inconvinience 😞
We have some other open issues ([288](https://github.com/mie-lab/trackintel/issues/288) or [286](https://github.com/mie-lab/trackintel/issues/286) ) that offer an easy entry to the framework. Let us know in the related issues if you are motivated to work on them.
