### ISSUE TITLE
trips with geometries cause error in id assignment

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#305]
The problem is that geopandas overrides the explode method of pandas (see issue [here](https://github.com/geopandas/geopandas/issues/2061)). This causes a problem [here](https://github.com/geopandas/geopandas/issues/2061) and [here](https://github.com/mie-lab/trackintel/blob/master/trackintel/preprocessing/triplegs.py#L270) as we want to access the original pandas explode method. 
I think the simplest fix would be to call the dataframe constructor before using explode. It is not too expensive and then we don't have to wait until the geopandas issue is fixed and we are not limited to only new geopandas versions.
E.g.:
`temp = pd.DataFrame(trips).explode("tpls")`
`temp = pd.DataFrame(trips).explode("spts")`

**Comment by bifbof** [comment]
I don't think this is a bug we need to fix. [Here](https://github.com/geopandas/geopandas/blob/4536b9203b0b2ff577d1368e4677ff93a4c82164/geopandas/geodataframe.py#L1600) it gets already checked if the column we provide is a geometry column and if not it is passed onto pandas DataFrame. Also the index gets set on the next line anyway ([here](https://github.com/mie-lab/trackintel/blob/99421d651d714b0265558810dea612b6fb66ed43/trackintel/preprocessing/triplegs.py#L265)).

**Comment by henrymartin1** [comment]
Ah, I see. Yes it was fixed in 0.9. In 8.2 it was still present --> https://github.com/geopandas/geopandas/blob/v0.8.2/geopandas/geodataframe.py#L974

**Comment by hong2223** [comment]
We decided to use a super function call to support geopandas/pandas
