### ISSUE TITLE
temporal_tracking_quality ends in infinite loop if start and end is at midnight

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#307]
I think the problem is the comparison [here](https://github.com/mie-lab/trackintel/blob/master/trackintel/analysis/tracking_quality.py#L274). If start and end are the same and both are at midnight they end up on different days. We could check if the first one is smaller than the second one rather than check for equality. This might be a corner case but we should avoid infinite loops at all costs.

Example code (results in infinite loop!)
```python
import datetime
import geopandas as gpd
import pandas as pd

from shapely.geometry import Point
from trackintel.analysis.tracking_quality import temporal_tracking_quality


p1 = Point(8.5067847, 47.4)
t1 = pd.Timestamp("1971-01-01 00:00:00", tz="utc")
t2 = pd.Timestamp("1971-01-01 00:00:00", tz="utc")

one_hour = datetime.timedelta(hours=1)

list_dict = [
    {"user_id": 0, "started_at": t1, "finished_at": t2, "geom": p1},
]
sp = gpd.GeoDataFrame(data=list_dict, geometry="geom", crs="EPSG:4326")
sp.index.name = "id"
print("start tracking quality")
quality = temporal_tracking_quality(sp, granularity="day")
print(quality)
```

**Comment by hong2223** [comment]
looking at just this example, I think we can also prefilter records who have `duration = 0` (since they do not contribute to the tracking quality anyway). I am not sure though if this will prevent other cases that trigger an infinite loop

**Comment by henrymartin1** [comment]
Yeah, I think that would also be OK. Maybe we should add a counter and a maximum number of iterations after which the execution stops and an error is raised. Similar to a "did not converge error". The user could then increase the number of iterations if he is convinced that this helps. 
In general it is annoying if you are in an infinite loop without noticing it...

**Comment by hong2223** [comment]
This is related to #304. We can filter negative and 0 duration records before the while loop. 
A counter that breaks after several iterations is also a good idea, I think we can set the default value like 30 or 60 (1 or 2 months) (a staypoint that last for 2 month is really long)
