### ISSUE TITLE
ENH for merge_staypoints() function

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#342]
The `merge_staypoints()` function in `trackintel/preprocessing/staypoints.py` would need a location_id column. I think this is not yet reflected in the docstring.

Also, the function is not yet added to the documentation.

**Comment by NinaWie** [comment]
True, thanks for pointing it out! I can take care of it

**Comment by hong2223** [comment]
Other things I found:
- I think by default the `location_id` should be in the agg_dict, e.g., `"location_id": "first"`, since only the same `location_id` will be merged.
- The user_id field becomes float type after the function. Perhaps it's changed in the `agg` operation? I am not quite sure.

BTW: thanks for the implementation, I find it very useful :)

**Comment by NinaWie** [comment]
I can't reproduce that the user_id becomes float after the function. The only thing I can find is that if the user_id is a float before, it stays a float after. Can you maybe check whether it was a float already in your input?

**Comment by NinaWie** [comment]
Okay never mind, I think it always happens if not all users of the staypoints df appear in the triplegs df, or the other way round. Because it has to insert NaNs then which is a float.
