### ISSUE TITLE
Bug in reading locations with extent from postgis

### ISSUE THREAD

**Issue by NinaWie** [mie-lab/trackintel#365]
I wrote a `locations` table to postgis with the function 
```
locs.as_locations.to_postgis(con=engine, name="locations", ...    )
```
I try to read it with 
```
sql = "SELECT * FROM schema.locations"
locs = ti.io.read_locations_postgis(sql, con=engine, extent="extent")
```
However, the extent is not a geometry in the output `locs`. I had to add the following line to make it work (the problem was the wkb encoding):
```
 locs["extent"] = locs["extent"].apply(lambda x: wkb.loads(bytes.fromhex(x)))
```

So we probably have to include this in the `read_locations_postgis` function. Please let me know if I just overlooked something, or whether I should go ahead with the changes.

**Comment by bifbof** [comment]
Yes that is indeed a bug. Good catch. :)
I hope it is okay that I created a PR for that (#367)
