### ISSUE TITLE
BUG/TST: Github action failed

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#370]
Our daily GitHub action failed 8 days ago when we had our last pull request. <s>I suspect that some changes from #361 is causing the error.</s>

**Comment by NinaWie** [comment]
Looks to me like it is only the codecov failing because I did not have a test for the case `if_crs_planar`. See [here](https://codecov.io/gh/mie-lab/trackintel/commit/1ff2323c868cfb82c0d0497cf57281c821e044d1#D4-37)
We can add a test for that and see if the problem is resolved

**Comment by hong2223** [comment]
> 

Ahh okay. I was more thinking of the scheduled tests - if you click on Actions you can see an array of failed scheduled tests since 7 days ago. The error message reads: `The job running on runner Hosted Agent has exceeded the maximum execution time of 360 minutes.` while our tests last usually ~15min

I don't know where the error comes from but suspect that we might have changed something in the last commit. But it also could be an error from the Github Action itself.

**Comment by hong2223** [comment]
> > 
> 
> Ahh okay. I was more thinking of the scheduled tests - if you click on Actions you can see an array of failed scheduled tests since 7 days ago. The error message reads: `The job running on runner Hosted Agent has exceeded the maximum execution time of 360 minutes.` while our tests last usually ~15min
> 
> I don't know where the error comes from but suspect that we might have changed something in the last commit. But it also could be an error from the Github Action itself.

I think the error comes from somewhere else than our PR. My fork has not yet integrated the last PR but still have these failed test since 7 days ago

**Comment by hong2223** [comment]
seems we are still having the same issue. I am reopening this.

**Comment by hong2223** [comment]
I think the error comes from package conflicts, namely the strict requirement of `pandas<=1.2.5` in our environment file. Deleting this solves the problem in my fork, but I'll wait for several days to ensure the error is fixed in the scheduled run before I create a PR.

This change would cause two tests to fail: `test_location_identification.test_multiple_users_with_only_one_location` and `test_triplegs.test_generate_trips_id_management`. for now I comment out these two, but later we need to fix the error.
