### ISSUE TITLE
id offset for generator functions

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#399]
The trackintel generator functions (`generate_triplegs`, `generate_trips`, ...) assign an ID to every instance. This ID plays a key role in many trackintel functions. If we want to merge trips from different sources/datasets to processes them jointly, we have to make sure that all trips have unique IDs. Therefore it would be great to have an ID offset as a parameter that allows IDs that do not start at 0.

**Comment by bifbof** [comment]
I am kind of against it, I see the motivation but adding the extra keyword is in my opinion not much more convenient than just using `gdf.index += offset`.
