### ISSUE TITLE
Geolife pfs to staypoints timedelta type error

### ISSUE THREAD

**Issue by NinaWie** [mie-lab/trackintel#420]
I get an error with the following code:
```
pfs_geolife, _ = read_geolife("Downloads/Geolife Trajectories 1.3/Data", print_progress=True)
pfs_geolife, sp_geolife = pfs_geolife.as_positionfixes.generate_staypoints(
    gap_threshold=24 * 60, include_last=True, print_progress=True, dist_threshold=200, time_threshold=30, n_jobs=4)
```
The error comes up in [this line](https://github.com/mie-lab/trackintel/blob/c401f3d7e38f1ef60e7db877f4793c7e78f6c3bd/trackintel/preprocessing/positionfixes.py#L409) and it's `ValueError: unknown type timedelta64[ns]`. I can also produce the error with the following simple test which only tests this line:
```
df = pfs_geolife[pfs_geolife["user_id"] == 135]
gap_times = pd.eval("((df.tracked_at - df.tracked_at.shift(1)) > 1)").to_numpy()
```
I've already updated my trackintel, numpy and pandas versions, but maybe it's still due to a version problem? Can you reproduce this error?
Thanks for looking into it!

**Comment by bifbof** [comment]
Hi Nina, thanks for the bug report. But it seems that I can't reproduce the bug on my computer. Which pandas version is currently installed in your environment?

**Comment by NinaWie** [comment]
Hi, I re-installed the environment and it's working now. Thanks for looking into it though, sorry I forgot to close the issue ;)
