### ISSUE TITLE
Remove simplification as it is provided  by geopandas as well

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#424]
As mentioned in the discussion in #418 we could remove the [trackintel.preprocessing.triplegs.smoothen_triplegs](https://trackintel.readthedocs.io/en/latest/modules/preprocessing.html#trackintel.preprocessing.triplegs.smoothen_triplegs) because the same wrapper is now provided directly by [geopandas](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.simplify.html)

**Comment by bifbof** [comment]
Will also close #400
