### ISSUE TITLE
Spatio-temporal aggregation of staypoints

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#43]
A single activity is often represented by several staypoints. Possible reasons for this are short movements within a building or GPS noise. An example would be that a person has several consecutive staypoints at home even though he never left the home. 
It would be nice to have the possibility to aggregate these staypoints spatio-temporally.

**Comment by hong2223** [comment]
Isn't that covered by `generate_locations` ? 
Or do you refer to a function to aggregate only **single** activity?

**Comment by henrymartin1** [comment]
Yes, it is more about single activities. In the SBB GC dataset we often had the issue that a single day of a person looks something like this: 
Home-->Work-->Work-->Work-->Home-->Shopping-->Home-->Home-->Home
So the same activity at the same location would be represented as consecutive staypoints which can be a problem if you look at summary statistics like average duration at work. A solution would be to aggregate these consecutive Staypoints to:
Home-->Work-->Shopping-->Home

It is a bit of a special case so it probably should not be prio 1.

**Comment by hong2223** [comment]
In the most simple case, this can be generated using `.groupby(["location_id", "activity"])` after running `generate_locations`. Of course this will give larger aggregations, but "simple" enough :).

**Comment by henrymartin1** [comment]
Same as: https://github.com/mie-lab/trackintel/issues/257
