### ISSUE TITLE
BUG: crs not set for trips or locations

### ISSUE THREAD

**Issue by NinaWie** [mie-lab/trackintel#442]
When I generate trips from staypoints and triplegs, the resulting Geodataframe has no crs defined, even though the crs was set for both staypoints and triplegs. 
e.g.:
```
>> print(sp.crs, legs.crs)
EPSG:2056 EPSG:2056
>> sp, legs, trips = ti.preprocessing.triplegs.generate_trips(act_sp, legs, gap_threshold=15, add_geometry=True)
>> print(trips.crs)
None
```
The same happens for generating locations. This is not intended, is it? For further processing of the data, I'd expect that the crs is adopted.

**Comment by henrymartin1** [comment]
Hey, this is definitely not intended. I think for trips this probably happens because we added the geometry support later and can probably fixed easily. For locations this might be a bit more difficult to fix because it is a geodataframe with two geometries, which is not standard....
