### ISSUE TITLE
Ability to read polyline geometries?

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#45]
At the moment trackintel can read .csv files with WKT or lat/lon columns. Should we include a parser for the (google polyline format)[https://developers.google.com/maps/documentation/utilities/polylinealgorithm]?

There is a (library)[https://github.com/hicsail/polyline] that already covers that which would mean that we get another dependency ...

**Comment by hong2223** [comment]
we decided not to implement the polyline format
