### ISSUE TITLE
Problem in index management with read/write csv functions

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#452]
When reading a trackintel csv file, the index becomes a column  and is lost as index (by default). The index is then replaced with a new index without name.
I think the default should be for the .csv files is that the index is kept as index. This could be done by setting the column "id" as the index by default which could be changed by the user if necessary.

```python
import trackintel as ti

from shapely.geometry import Point
import pandas as pd
import geopandas as gpd
import datetime
p1 = Point(8.5067847, 47.4)
p2 = Point(8.5067847, 47.5)
p3 = Point(8.5067847, 47.6)

t1 = pd.Timestamp("1971-01-01 00:00:00", tz="utc")
t2 = pd.Timestamp("1971-01-01 05:00:00", tz="utc")
t3 = pd.Timestamp("1971-01-02 07:00:00", tz="utc")
one_hour = datetime.timedelta(hours=1)

list_dict = [
    {"user_id": 0, "started_at": t1, "finished_at": t2, "geom": p1},
    {"user_id": 0, "started_at": t2, "finished_at": t3, "geom": p2},
    {"user_id": 1, "started_at": t3, "finished_at": t3 + one_hour, "geom": p3},
]
sp = gpd.GeoDataFrame(data=list_dict, geometry="geom", crs="EPSG:4326")
sp.index.name = "id"

# sp.rename(inplace=True, columns={"geom": "geometry"})
# sp.drop(columns=['finished_at'], inplace=True)


sp.as_staypoints.to_csv("test2.csv")
sp2 = ti.io.read_staypoints_csv("test2.csv")
print(sp.index.name, print(sp2.index.name))
```
This prints: `id None`

Maybe this can be fixed on the fly with #451

**Comment by bifbof** [comment]
I don't think we should change the default value of the `index_col` argument.
One gets a warning for the code above code hinting that this might be a problem. 
In my opinion the warning is even a bit much, as one expects pandas default behavior from which we deviate.
Further we don't say anywhere that `id` should be the index name, thus this can create a lot of confusion with unrelated columns.

Can I close this issue?

**Comment by henrymartin1** [comment]
Hm... I am not sure. I think it would be really great to be able to write and read data with trackintel using only the default arguments. 
E.g., that this code
```
sp.as_staypoints.to_csv("test2.csv")
sp2 = ti.io.read_staypoints_csv("test2.csv")
```
would lead to `sp` being identical to `sp2`. @hongyeehh or @NinaWie do you have an opinion on whether or not we should close this issue?

**Comment by hongyeehh** [comment]
I somewhat agree with @bifbof. With your test code, we get a `UserWarning` that warns we implicitly assume the default index, which is sufficient IMO. We can control the id assignment with index_col, e.g., `sp2 = ti.io.read_staypoints_csv("test2.csv", index_col="id")` will create the desired behaviour.

Setting `id` as the default parameter will likely cause many errors when reading, especially if the file is not coming from (written by) trackintel.

**Comment by henrymartin1** [comment]
then we'll close it ;-)
