### ISSUE TITLE
BUG: generate_trips

### ISSUE THREAD

**Issue by jpmorris22** [mie-lab/trackintel#454]
Working through the tutorial: 
When I run this code: 
from trackintel.preprocessing.triplegs import generate_trips
sp, tpls, trips = ti.preprocessing.triplegs.generate_trips(sp, tpls, gap_threshold=15, add_geometry=True)

trips.count()

Here is the output:
UserWarning: Override column 'trip_id' in copy of triplegs.
  warnings.warn(f"Override column 'trip_id' in copy of triplegs.")
UserWarning: Override column(s) Index(['prev_trip_id', 'next_trip_id', 'trip_id'], dtype='object') in copy of staypoints.
  warnings.warn(f"Override column(s) {intersection} in copy of staypoints.")
ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)

user_id                     15
started_at                  15
finished_at                 15
geom                        15
origin_staypoint_id          1
destination_staypoint_id     1
dtype: int64

**Comment by hong2223** [comment]
Hi jpmorris22,

As far as I can see from the issue, the trip generation runs correctly and produces some results. The warnings are for notification and shall not affect the trip generation result. Could you be more specific about the bug?
