### ISSUE TITLE
Missing Data: tutorial geolife

### ISSUE THREAD

**Issue by jpmorris22** [mie-lab/trackintel#455]
I'm working through the tutorial where it gives an example of how to handle geolife files. I am looking for a directory with geolife data to run the code, but there doesn't appear to be a relevant directory.

Load example geolife dataset:

pfs, _ = ti.io.dataset_reader.read_geolife('../tests/data/geolife_long')

plot the raw positionfixes:

pfs.as_positionfixes.plot(plot_osm=True)

Additionally, this code depends on the geolife directory:

for the modal split we load a special subset of geolife dataset with tripleg modes:

pfs, labels = ti.io.dataset_reader.read_geolife('../tests/data/geolife_modes')

sp and tpls are generated:

pfs, sp = pfs.as_positionfixes.generate_staypoints(method="sliding", dist_threshold=25, time_threshold=5)
_, tpls = pfs.as_positionfixes.generate_triplegs(sp, method="between_staypoints")

the mode labels are assigned to each tpls:

tpls_with_modes = ti.io.dataset_reader.geolife_add_modes_to_triplegs(tpls, labels)
tpls_with_modes.head(5)

**Comment by hong2223** [comment]
Hi jpmorris22,

Thanks for the issue. I have tested the tutorial code snippets, and it runs without an error. 
The data you referred to is stored in the `./tests/data/` folder. I recommend cloning the whole trackintel repo and executing the tutorial notebook in the folder where it is placed. These relative file paths will then resolve correctly.
