### ISSUE TITLE
ValueError: unknown type timedelta64[ns] when as_positionfixes.generate_staypoints()

### ISSUE THREAD

**Issue by oleksandrkarasov** [mie-lab/trackintel#466]
Dear developers,
First of all, many thanks for this valuable software! Unfortunately, I face the error when trying to execute as_positionfixes.generate_staypoints() for basic trackintel dataframe (![image](https://user-images.githubusercontent.com/23281934/225071803-b44ff86c-c3c7-4943-a16f-256519d32a2b.png)). I tried to import both csv and gdf, but receive the following error:

ValueError                                Traceback (most recent call last)
Cell In[43], line 2
      1 pfs = ti.read_positionfixes_csv('/projappl/project_2004147/twitter/simple_geodata.csv',tz='UTC',crs='EPSG:4326')
----> 2 pfs.as_positionfixes.generate_staypoints()

File ~/.local/lib/python3.10/site-packages/trackintel/model/positionfixes.py:84, in PositionfixesAccessor.generate_staypoints(self, *args, **kwargs)
     77 @_copy_docstring(generate_staypoints)
     78 def generate_staypoints(self, *args, **kwargs):
     79     """
     80     Generate staypoints from this collection of positionfixes.
     81 
     82     See :func:`trackintel.preprocessing.positionfixes.generate_staypoints`.
     83     """
---> 84     return ti.preprocessing.positionfixes.generate_staypoints(self._obj, *args, **kwargs)

File ~/.local/lib/python3.10/site-packages/trackintel/preprocessing/positionfixes.py:128, in generate_staypoints(positionfixes, method, distance_metric, dist_threshold, time_threshold, gap_threshold, include_last, print_progress, exclude_duplicate_pfs, n_jobs)
    125 # TODO: tests using a different distance function, e.g., L2 distance
    126 if method == "sliding":
    127     # Algorithm from Li et al. (2008). For details, please refer to the paper.
--> 128     sp = applyParallel(
    129         pfs.groupby("user_id", as_index=False),
    130         _generate_staypoints_sliding_user,
    131         n_jobs=n_jobs,
    132         print_progress=print_progress,
    133         geo_col=geo_col,
    134         elevation_flag=elevation_flag,
    135         dist_threshold=dist_threshold,
    136         time_threshold=time_threshold,
    137         gap_threshold=gap_threshold,
    138         distance_metric=distance_metric,
    139         include_last=include_last,
    140     ).reset_index(drop=True)
    142     # index management
    143     sp["staypoint_id"] = sp.index

File ~/.local/lib/python3.10/site-packages/trackintel/preprocessing/util.py:81, in applyParallel(dfGrouped, func, n_jobs, print_progress, **kwargs)
     47 def applyParallel(dfGrouped, func, n_jobs, print_progress, **kwargs):
     48     """
     49     Funtion warpper to parallelize funtions after .groupby().
     50 
   (...)
     79     >>> applyParallel(tpfs.groupby("user_id", as_index=False), func, n_jobs=2)
     80     """
---> 81     df_ls = Parallel(n_jobs=n_jobs)(
     82         delayed(func)(group, **kwargs) for _, group in tqdm(dfGrouped, disable=not print_progress)
     83     )
     84     return pd.concat(df_ls)

File /CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/joblib/parallel.py:1085, in Parallel.__call__(self, iterable)
   1076 try:
   1077     # Only set self._iterating to True if at least a batch
   1078     # was dispatched. In particular this covers the edge
   (...)
   1082     # was very quick and its callback already dispatched all the
   1083     # remaining jobs.
   1084     self._iterating = False
-> 1085     if self.dispatch_one_batch(iterator):
   1086         self._iterating = self._original_iterator is not None
   1088     while self.dispatch_one_batch(iterator):

File /CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/joblib/parallel.py:901, in Parallel.dispatch_one_batch(self, iterator)
    899     return False
    900 else:
--> 901     self._dispatch(tasks)
    902     return True

File /CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/joblib/parallel.py:819, in Parallel._dispatch(self, batch)
    817 with self._lock:
    818     job_idx = len(self._jobs)
--> 819     job = self._backend.apply_async(batch, callback=cb)
    820     # A job can complete so quickly than its callback is
    821     # called before we get here, causing self._jobs to
    822     # grow. To ensure correct results ordering, .insert is
    823     # used (rather than .append) in the following line
    824     self._jobs.insert(job_idx, job)

File /CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/joblib/_parallel_backends.py:208, in SequentialBackend.apply_async(self, func, callback)
    206 def apply_async(self, func, callback=None):
    207     """Schedule a func to be run"""
--> 208     result = ImmediateResult(func)
    209     if callback:
    210         callback(result)

File /CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/joblib/_parallel_backends.py:597, in ImmediateResult.__init__(self, batch)
    594 def __init__(self, batch):
    595     # Don't delay the application, to avoid keeping the input
    596     # arguments in memory
--> 597     self.results = batch()

File /CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/joblib/parallel.py:288, in BatchedCalls.__call__(self)
    284 def __call__(self):
    285     # Set the default nested backend to self._backend but do not set the
    286     # change the default number of processes to -1
    287     with parallel_backend(self._backend, n_jobs=self._n_jobs):
--> 288         return [func(*args, **kwargs)
    289                 for func, args, kwargs in self.items]

File /CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/joblib/parallel.py:288, in <listcomp>(.0)
    284 def __call__(self):
    285     # Set the default nested backend to self._backend but do not set the
    286     # change the default number of processes to -1
    287     with parallel_backend(self._backend, n_jobs=self._n_jobs):
--> 288         return [func(*args, **kwargs)
    289                 for func, args, kwargs in self.items]

File ~/.local/lib/python3.10/site-packages/trackintel/preprocessing/positionfixes.py:406, in _generate_staypoints_sliding_user(df, geo_col, elevation_flag, dist_threshold, time_threshold, gap_threshold, distance_metric, include_last)
    404 time_threshold = pd.Timedelta(time_threshold, unit="minutes")
    405 # to numpy as access time of numpy array is faster than pandas Series
--> 406 gap_times = pd.eval("((df.tracked_at - df.tracked_at.shift(1)) > gap_threshold)").to_numpy()
    408 # put x and y into numpy arrays to speed up the access in the for loop (shapely is slow)
    409 x = df[geo_col].x.to_numpy()

File ~/.local/lib/python3.10/site-packages/pandas/core/computation/eval.py:358, in eval(expr, parser, engine, truediv, local_dict, global_dict, resolvers, level, target, inplace)
    356 eng = ENGINES[engine]
    357 eng_inst = eng(parsed_expr)
--> 358 ret = eng_inst.evaluate()
    360 if parsed_expr.assigner is None:
    361     if multi_line:

File ~/.local/lib/python3.10/site-packages/pandas/core/computation/engines.py:81, in AbstractEngine.evaluate(self)
     78     self.result_type, self.aligned_axes = align_terms(self.expr.terms)
     80 # make sure no names in resolvers and locals/globals clash
---> 81 res = self._evaluate()
     82 return reconstruct_object(
     83     self.result_type, res, self.aligned_axes, self.expr.terms.return_type
     84 )

File ~/.local/lib/python3.10/site-packages/pandas/core/computation/engines.py:122, in NumExprEngine._evaluate(self)
    120 scope = env.full_scope
    121 _check_ne_builtin_clash(self.expr)
--> 122 return ne.evaluate(s, local_dict=scope)

File ~/.local/lib/python3.10/site-packages/numexpr/necompiler.py:822, in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)
    819 arguments = getArguments(names, local_dict, global_dict)
    821 # Create a signature
--> 822 signature = [(name, getType(arg)) for (name, arg) in
    823              zip(names, arguments)]
    825 # Look up numexpr if possible.
    826 numexpr_key = expr_key + (tuple(signature),)

File ~/.local/lib/python3.10/site-packages/numexpr/necompiler.py:822, in <listcomp>(.0)
    819 arguments = getArguments(names, local_dict, global_dict)
    821 # Create a signature
--> 822 signature = [(name, getType(arg)) for (name, arg) in
    823              zip(names, arguments)]
    825 # Look up numexpr if possible.
    826 numexpr_key = expr_key + (tuple(signature),)

File ~/.local/lib/python3.10/site-packages/numexpr/necompiler.py:700, in getType(a)
    698 if kind == 'U':
    699     raise ValueError('NumExpr 2 does not support Unicode as a dtype.')
--> 700 raise ValueError("unknown type %s" % a.dtype.name)

ValueError: unknown type timedelta64[ns]
​
Could you, please, help me to understand what may cause this error?

**Comment by eowyzh** [comment]
Dear developers:
        Unfortunately, I met the same problem here, even though I used the example data.
        Here is the detailed information:
        Data:examples\\data\\geolife_trajectory.csv
        1.user_id                     int64
          tracked_at    datetime64[ns, UTC]
          elevation                   int64
          accuracy                    int64
          geom                     geometry
          dtype: object
        2.<class 'pandas._libs.tslibs.timestamps.Timestamp'>
        3.pandas 1.5.3
          trackintel 1.1.13
       Looking forward to your reply, thx.

 ps: error information
  File "D:\人类移动性计算结果整理\trackintel.py", line 52, in <module>
    pfs, sp = pfs.as_positionfixes.generate_staypoints(method='sliding')

  File "D:\Anaconda3\lib\site-packages\trackintel\model\positionfixes.py", line 84, in generate_staypoints
    return ti.preprocessing.positionfixes.generate_staypoints(self._obj, *args, **kwargs)

  File "D:\Anaconda3\lib\site-packages\trackintel\preprocessing\positionfixes.py", line 128, in generate_staypoints
    sp = applyParallel(

  File "D:\Anaconda3\lib\site-packages\trackintel\preprocessing\util.py", line 81, in applyParallel
    df_ls = Parallel(n_jobs=n_jobs)(

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\joblib\parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)

  File "D:\Anaconda3\lib\site-packages\trackintel\preprocessing\positionfixes.py", line 406, in _generate_staypoints_sliding_user
    gap_times = pd.eval("((df.tracked_at - df.tracked_at.shift(1)) > gap_threshold)").to_numpy()

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\eval.py", line 358, in eval
    ret = eng_inst.evaluate()

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\engines.py", line 81, in evaluate
    res = self._evaluate()

  File "C:\Users\micky\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\engines.py", line 122, in _evaluate
    return ne.evaluate(s, local_dict=scope)

  File "D:\Anaconda3\lib\site-packages\numexpr\necompiler.py", line 814, in evaluate
    signature = [(name, getType(arg)) for (name, arg) in

  File "D:\Anaconda3\lib\site-packages\numexpr\necompiler.py", line 814, in <listcomp>
    signature = [(name, getType(arg)) for (name, arg) in

  File "D:\Anaconda3\lib\site-packages\numexpr\necompiler.py", line 692, in getType
    raise ValueError("unknown type %s" % a.dtype.name)

ValueError: unknown type timedelta64[ns]

**Comment by henrymartin1** [comment]
Dear @eowyzh,
thank you for submitting the report! I think this problem is related to the use of `pd.eval()` in one of our functions [here](https://github.com/mie-lab/trackintel/blob/master/trackintel/preprocessing/positionfixes.py#L406). The same error is also discussed at StackOverflow [here](https://stackoverflow.com/questions/22052337/unable-to-subtract-datetime64-using-dataframe-eval)

However, I am unable to reproduce the problem even when using your pandas version. Could you provide us with a minimal working example (code snipped) that uses the data from `examples\data\geolife_trajectory.csv` and leads to this error? THis would help us to make sure that we can avoid this problem.

Until we fixed the problem you can try to update your pandas version (>2.0) but I am not sure if this fixes the problem as I could not reproduce it yet.

@NinaWie & @hong2223 : I think we should get rid of the `pd.eval()` expression as it seems to lead to errors and is not necessary anyways.

**Comment by henrymartin1** [comment]
#471 We have now replaced the eval expression which should solve this issue. Please update to the newest trackintel version (1.2), this should solve the issue. Please let us know if the issue persists.
