### ISSUE TITLE
Replace simplify library using shapely

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#47]
The implemented version of the dougals-peucker algorithm uses the external library `simplificaiton`. However, shapely also has an implementation of douglas-peucker available: https://shapely.readthedocs.io/en/latest/manual.html#object.simplify

We should use the shapely version to get rid of the additional dependency

**Comment by henrymartin1** [comment]
At the moment the default installation using the environment file fails because simplification is not working with python 3.9. I already had trouble installing trackintel because of this library several times. I really think that we should remove it because it is not worth it....

**Comment by hong2223** [comment]
Agree that we should replace it with shapely
