### ISSUE TITLE
BLD: pypi-publish workflow stopped working 

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#472]
It seems that automatic publishing to pypi is not working anymore. 
the message stays at `Waiting for a runner to pick up this job...` for over a day and failed because of timeout: 

> [Build and publish Python distr to TestPyPI](https://github.com/mie-lab/trackintel/actions/runs/4732944306/jobs/8399749683)
> This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.

**Comment by henrymartin1** [comment]
fixed with a directly via commit https://github.com/mie-lab/trackintel/commit/11cd259492951424296243b0ecfa94ba55d1d62b
