### ISSUE TITLE
problem with read_positionfixes_gpd 

### ISSUE THREAD

**Issue by eowyzh** [mie-lab/trackintel#473]
Dear developers,
         In the function "read_positionfixes_gpd", when the data type of 'userid' is 'str' type, the analysis function 'as_positionfixes.generate_triplegs' face the error of 'unsupported operand type(s) for -: 'str' and 'str''.When I changed the data type of 'userid' to int64, which has the same type as the example data(examples\\data\\geolife_trajectory.csv), the error was solved, I'm not sure this problem is not a common case. Could you please, in subsequent program updates, 'userid' can support str type as input, or in the help documentation, indicate the data type of each parameter. thx~

ps: error details
1.The version of mine trackintel and pandas installation:
trackintel 1.2.0
pandas 1.5.3
2.the input data type:
user_id                    object
date                       object
hour                       object
x                         float64
y                         float64
att1                        int64
att2                        int64
tracked_at    datetime64[ns, UTC]
xy                       geometry
dtype: object

user_id                    string
date                       object
hour                       object
x                         float64
y                         float64
att1                        int64
att2                        int64
tracked_at    datetime64[ns, UTC]
xy                       geometry
dtype: object
I test the ’userid' type as  both ‘str' and 'object'
3.error information 
pfs, sp = pfs.as_positionfixes.generate_staypoints(method='sliding')
pfs, tpls = pfs.as_positionfixes.generate_triplegs(sp, method='between_staypoints')

File ~\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File d:\人类移动性计算结果整理\trackintel.py:46
    pfs, tpls = pfs.as_positionfixes.generate_triplegs(sp, method='between_staypoints')

  File ~\anaconda3\lib\site-packages\trackintel-1.2.0-py3.10.egg\trackintel\model\positionfixes.py:93 in generate_triplegs
    return ti.preprocessing.positionfixes.generate_triplegs(self._obj, staypoints, *args, **kwargs)

  File ~\anaconda3\lib\site-packages\trackintel-1.2.0-py3.10.egg\trackintel\preprocessing\positionfixes.py:279 in generate_triplegs
    cond_new_user = ((pfs["user_id"] - pfs["user_id"].shift(1)) != 0) & pd.isna(pfs["staypoint_id"])

  File ~\anaconda3\lib\site-packages\pandas\core\ops\common.py:72 in new_method
    return method(self, other)

  File ~\anaconda3\lib\site-packages\pandas\core\arraylike.py:110 in __sub__
    return self._arith_method(other, operator.sub)

  File ~\anaconda3\lib\site-packages\pandas\core\series.py:6259 in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)

  File ~\anaconda3\lib\site-packages\pandas\core\base.py:1325 in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)

  File ~\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:218 in arithmetic_op
    res_values = op(left, right)

  File ~\anaconda3\lib\site-packages\pandas\core\ops\common.py:72 in new_method
    return method(self, other)

  File ~\anaconda3\lib\site-packages\pandas\core\arraylike.py:110 in __sub__
    return self._arith_method(other, operator.sub)

  File ~\anaconda3\lib\site-packages\pandas\core\arrays\string_.py:511 in _cmp_method
    result[valid] = op(self._ndarray[valid], other)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by NinaWie** [comment]
Thanks for notifying us about this bug! Trackintel usually supports string user IDs and we did not intentionally enforce integer IDs in the `read_positionfixes_gpd` function. We will fix it in the next version.
