### ISSUE TITLE
`obj.as_xyz` does not necessarily validate data

### ISSUE THREAD

**Issue by bifbof** [mie-lab/trackintel#476]
The pattern `sp.as_staypoints` is regularly used in the codebase to verify that the data is valid.
It is intended that it calls the [`StaypointsAccessor`](https://github.com/mie-lab/trackintel/blob/11ff487b1596d0da5f346446df0fd340df433210/trackintel/model/staypoints.py#L46) `__init__` function, which in turn calls the `_validate` function.
But the accessor classes are cached ([here](https://github.com/pandas-dev/pandas/blob/1a23779f09abc6ebf908d66ee88b973b767e2e3c/pandas/core/accessor.py#L151)). Thus the `StaypointsAccessor` class is only created once per object and all follow-up `sp.as_staypoints` calls will always suceed.

Let's consider the following example
```python
from shapely.geometry import Point
import pandas as pd
import geopandas as gpd
import trackintel as ti

p1 = Point(8.5067847, 47.4)
t1 = pd.Timestamp("1971-01-01 04:00:00", tz="utc")
pfs = gpd.GeoDataFrame(data=[{"user_id": 0, "tracked_at": t1, "geom": p1}], geometry="geom", crs="EPSG:4326")
pfs.index.name = "id"
pfs.as_positionfixes # does call "_verify"
pfs.drop(columns="tracked_at", inplace=True)
pfs.as_positionfixes # should not succeed as column "tracked_at" is required
```

Here the second assert goes through although the data is not valid anymore.

This leads to two potential bugs ([here](https://github.com/mie-lab/trackintel/blob/11ff487b1596d0da5f346446df0fd340df433210/trackintel/analysis/location_identification.py#L52) and [here](https://github.com/mie-lab/trackintel/blob/11ff487b1596d0da5f346446df0fd340df433210/trackintel/analysis/location_identification.py#L129)).
In this two places we should call `_validate` manually.

**Comment by henrymartin1** [comment]
Ah wow... I didn't expect that the accessors are cached... 
In this case it would probably make sense to implement the validation independent from the accessor and then call it manually as you suggested.
