### ISSUE TITLE
Extract places from staypoints

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#51]
The term **places** could be discussed, as most literature refers to it as **locations**. 

Currently, places extraction is performed per-user, would it be necessary to include a dataset-level extraction?

**Comment by hong2223** [comment]
We agreed that 
1. The user should be able to choose between "user place" and "dataset place" via an input parameter.
2. The function `cluster_staypoints` should return both the staypoints (with place_id) and the places.
3. The name "place" could be changed into "location". need more reference regarding the naming.

**Comment by henrymartin1** [comment]
I think we can consider that as solved by now right?

**Comment by hong2223** [comment]
> I think we can consider that as solved by now right?

The first point is not implemented yet (dataset level locations)
