### ISSUE TITLE
Check if id preservation + id propagation works for all datatypes

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#56]
We should check (and write a test) if ids are properly stored in all datatypes. 

E.g., 
positionfixes -> triplegs (tripleg_id should exist in positionfixes)
positionfixes -> staypoints (staypoint_id should exist in positionfixes)
triplegs/staypoints -> trips (trip_id, prev_trip_id, next_trip_id in staypoints/triplegs)
staypoins->locations (staypoints have location id)
trips -> tours (trips should have tour id)

**Comment by henrymartin1** [comment]
At the moment I can confirm the following problems:
- `as_positionfixes.extract_triplegs` does return a dataframe with non unique index (but a unique column 'id'). 
- `as_positionfixes.extract_staypoints` does still return the column `id` (but with unique index)

**Comment by hong2223** [comment]
> positionfixes -> triplegs (tripleg_id should exist in positionfixes) 
In Case 1 of the `generate_triplegs` function for positionfixes, no 'tripleg_id' field is assigned to the new positionfixes

**Comment by henrymartin1** [comment]
Originally this issue was concerning the problem with altering the input data and with not having IDs as an index. It now only concerns the problem of changing the input dataframe. The problem of having IDs as pandas index is described in Issue #97
