### ISSUE TITLE
start and endpoint for trip model

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#57]
I think trips in trackintel should have the start and end point as geometry. Even though from the perspective of creating trips from staypoints this is redundant but in real-life use cases it might appear that we only analyze trips without having access to staypoints.

- Add columns geom_start and geom_end as required (and with a fixed name I guess...)
- Add column primary_mode as an optional column

**Comment by hong2223** [comment]
Would it be enough for trips to contain start and end ids of staypoints instead of their geometry? I think storing the geometry 3 times is not so elegant...

**Comment by henrymartin1** [comment]
I think that is what we are usually doing and what is implemented in trackintel at the moment. However this is coming more from a database perspective where you have access to all data aggregation levels (trackpoints->staypoints/triplegs->trips). Here it makes a lot of sense to only reference the ids  (like we are doing at the moment). 
In practice I see two problems with that:
- There are cases where you only have your data on the trip level without having access to staypoints. Then the trips should have start and end geometry. So in a way, all the data level should be self-sustained or complete...
- I think that there are trip based analyses where you will need the start and endpoints of these trips. Here I think the python workflow and the database workflow are different. In SQL it would be normal to join the data ad-hoc in the analysis or export query ( or you would create a view of the combined data and use this view). We don't really have this option in python and if you join the data ad-hoc for further processing or exporting then you might already do it right away.

**Comment by hong2223** [comment]
- Aren't the trips already self-sustained? E.g., we can access the start- and end- points using trips.geometry.x[0] and x[-1] (just as an example) whenever we need them in the analysis. IMO, this pre-fetching processing won't take too much running time. Also, we would also have analyses that don't require point info. As the fundamental data model ('trips') I think it's nice to keep it as simple as possible.
- I am not sure if I understand your argument, but I think if you have the ids in Python it's straightforward to link the tables through pandas.merge(); it's also rather efficient for large datasets. We could regard the start- and end- ids as an optional column: if trips are generated by the trackintel we assign the two columns, otherwise, it is not required.

Is there any case that I did not think about?

BTW, if the trips are simplified (using shaply.simplify() for example), the Linestring points could change and we need to also re-assign the start- and end- point geometry.

**Comment by hong2223** [comment]
> * Aren't the trips already self-sustained? E.g., we can access the start- and end- points using trips.geometry.x[0] and x[-1] (just as an example) whenever we need them in the analysis. IMO, this pre-fetching processing won't take too much running time. Also, we would have analyses that don't require point info. As the fundamental data model ('trips') I think it's nice to keep it as simple as possible.
> * I am not sure if I understand your argument, but I think if you have the ids in Python it's straightforward to link the tables through pandas.merge(); it's also rather efficient for large datasets. We could regard the start- and end- ids as an optional column: if trips are generated by the trackintel we assign the two columns, otherwise, it is not required.
> 
> Is there any case that I did not think about?
> 
> BTW, if the trips are simplified (using shaply.simplify() for example), the Linestring points could change and we need to also re-assign the start- and end- point geometry.

Originally I misunderstood the `trip` definition; if the trip container does not have a 'geometry' column, I think it is a good idea to store the start and end point's geometry as extra fields.

**Comment by henrymartin1** [comment]
I think I will tackle this issue soon as I will require some functions that need to access trip start and end points.
Do we agree on the following points?
- Trips get an optional __multipoint__ geometry column that consists of the start and the endpoint. I can see that multipoint seems weird on a first glance this is how it is implemented in shapely (e.g., linestring.boundary or triplegs.boundary should yield exactly this result). Multipoint would allow trips to have a single valid geometry column that can be called via trips.geometry. 
- If we generate trips from staypoints/triplegs these trips will receive this geometry column. 
- I can implement functions that access the geometry and raise an exception if it does not exist. (specifically I am planning an accessor that wraps around the spatial_filter method to filter trips that start or end in a polygon)

**Comment by NinaWie** [comment]
I'll try to take care of this issue now as we discussed this morning, just fyi :)

**Comment by henrymartin1** [comment]
Awesome!
