### ISSUE TITLE
yumuv dataset not available in the examples folder

### ISSUE THREAD

**Issue by SebastianoX** [mie-lab/trackintel#608]
Hello,
This is really a great work, thanks for sharing it.

In the paper you mention the yumuv and the geolife mobility dataset. The geolife is a well known one and open sourced by microsoft. I could not find the yumuv dataset. Is it open sourced?

**Comment by hongyeehh** [comment]
Hi,

Thanks for your interest in our work. Unfortunately, we cannot open-source the yumuv dataset. You can find the analysis result of yumuv in [Trackintel_case_study.pdf](https://github.com/mie-lab/trackintel/blob/master/examples/Trackintel_case_study.pdf) and examples of other (open-sourced) dataset in [preprocess_trajectories.py](https://github.com/mie-lab/trackintel/blob/master/examples/preprocess_trajectories.py)

**Comment by SebastianoX** [comment]
Thank you for the quick reply, I understand — this closes the issue. Keep up with the great work
