### ISSUE TITLE
Fixed column names in read CSV functions

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#64]
The read csv functions implicitly assume fixed column names. We should somehow allow flexible column names as input. But internally within trackintel, I think it is good to use a consistent set of column names for each attribute.

We could add additional parameters in each `read_csv` function to map the original column names to the framework's name. Additionally, we could use column name checks in each accessor, and provide a column name mapping (renaming) function before using the accessor.

The workflow would then look like: 

> trackintel(read_data(rename) -> process_data)

 or 

> read using pandas or geopandas -> rename -> trackintel(through accessor -> process_data) 

or 

> read using pandas or geopandas -> trackintel(function wrapper(rename) -> process_data) 

What do you think of the workflow?

**Comment by henrymartin1** [comment]
>  We should somehow allow flexible column names as input.
Yes, I immediately saw the necessity of this when processing the data you send me ;-) What do you think of having an optional renaming dict that allows you to rename one or several columns as input?

> Additionally, we could use column name checks in each accessor, and provide a column name mapping (renaming) function before using the accessor.
I am not sure if I think it is a good idea to allow a mapping in the accessor. I think the accessor should check the names (it should do so already) and maybe hint you towards another function that can be applied to your dataframes to make them trackintel conform (which would basically be a renaming wrapper...).

**Comment by hong2223** [comment]
> > We should somehow allow flexible column names as input.
> 
> Yes, I immediately saw the necessity of this when processing the data you send me ;-) What do you think of having an optional renaming dict that allows you to rename one or several columns as input?
> 

What I have in mind is the implementation [here](https://scikit-mobility.github.io/scikit-mobility/reference/data_structures.html#skmob.core.trajectorydataframe.TrajDataFrame). We require the user to input the column names (like `geom=geometry, user_id = uid`), and internally in our function we rename the columns to ensure consistency, e.g., `df.rename(columns={geometry: geom, uid: user_id })`

> > Additionally, we could use column name checks in each accessor, and provide a column name mapping (renaming) function before using the accessor.
> 
> I am not sure if I think it is a good idea to allow a mapping in the accessor. I think the accessor should check the names (it should do so already) and maybe hint you towards another function that can be applied to your dataframes to make them trackintel conform (which would basically be a renaming wrapper...).

Yes, we need this helper function which in the most simple way accepts parameter pairs (like above `geom=geometry, user_id = uid`).
