### ISSUE TITLE
publish package on pypi and implement workflow to publish new releases automatically

### ISSUE THREAD

**Issue by svenruf** [mie-lab/trackintel#82]
I tested the publication on test.pypi.org with my fork and the workflow works correctly. I think it would be good if someone of MIE-lab creates the accounts (both on test.pypi.org and pypi.org. The workflow needs the API Tokens to be stored in github.secrets.

**Comment by henrymartin1** [comment]
Yes, good point! I'll send you the account details.

**Comment by svenruf** [comment]
@henrymartin1 I think it would be a good idea to create the workflow in a designated branch. I'm not able to create one, could you do this? And I also don't have the permission to access github.secrets, could you insert the API key?

**Comment by svenruf** [comment]
The workflow is set up in the test pypi branch. I changed the trigger to "on: release". I will prepare a checklist for a new release. Once we discussed the integration and the checklist I will make a pull request (maybe also with the "real" pypi workflow).
