### ISSUE TITLE
Test for preprocessing.positionfixes

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#89]
Tests are needed for the different cases in 'generate_triplegs' function from preprocessing.positionfixes.
Case 1 and case 2 do not assign 'tripleg_id' to the original positionfixes df.

**Comment by henrymartin1** [comment]
I agree that the generate_tripleg function is currently very complex and partially untested. 
Important steps would be:
- Break up the different cases using a "method" argument that is given by the user
- Encapsulated the different cases into functions 
- Create tests for the different functions
