### ISSUE TITLE
Binder points to wrong notebook

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#9]
The Binder link in our readme still points to the notebook in a different github repository:
https://mybinder.org/v2/gh/henrymartin1/trackintel/master?filepath=examples%2Fexample_geolife%2FTrackintel_introduction.ipynb

**Comment by svenruf** [comment]
Needs a working environment file, see issue #80. I will fix this as soon as #79 is integrated.

**Comment by henrymartin1** [comment]
I have integrated #79. You are ready to go!
