### ISSUE TITLE
automatic version badge updates

### ISSUE THREAD

**Issue by svenruf** [mie-lab/trackintel#90]
At the moment the version badge in [readme.md](https://github.com/mie-lab/trackintel/blob/master/README.md) is set manually. with [badge fury](https://badge.fury.io) this would be possible automatically. This would reduce the manual effort needed when releasing a new version. (related to #82)

**Comment by henrymartin1** [comment]
Sounds great, let's get it!

**Comment by svenruf** [comment]
a webhook is needed, settings see [here](https://badge.fury.io/for/gh)

**Comment by hong2223** [comment]
I am also not able to add, maybe we could try [this](https://badge.fury.io/for/py) once we have it published in pypi

**Comment by hong2223** [comment]
closed with pypi version badge
