### ISSUE TITLE
Data quality assessments

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#92]
The data quality assessments by time (tracking quality per hour/day/week per user) are already implemented and need to be integrated into trackintel. The current idea is to put it into the `analysis` module and output a quality df. The user can then decide whether to plot or save it.

Question: how do we measure data quality spatially?

**Comment by henrymartin1** [comment]
Hm... good question. I think spatial data quality is very hard to evaluate maybe we should focus on temporal completeness first.
In the past we sometimes analyzed the "accuracy" attribute of GPS trackpoints. For trackpoints we could maybe calculate the  average distance between two consecutive trackpoints?
