### ISSUE TITLE
tests (and test data) missing for (read) tours

### ISSUE THREAD

**Issue by svenruf** [mie-lab/trackintel#98]
function tours_from_gpd is not tested (#93) 
function read_tours_csv is not available. is this correct or should it be added?

**Comment by hong2223** [comment]
I think this is because tours is not yet fully supported. I'll add function signatures to remind us later.

**Comment by henrymartin1** [comment]
> 
> 
> I think this is because tours is not yet fully supported. I'll add function signatures to remind us later.

I think adding function signatures is right thing to do. Our future selfs will thank you for that :D
